require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# permissions_path = '../node_modules/react-native-permissions/ios'

# pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
# pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
# pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
# pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
# pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text', :modular_headers => true
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

platform :ios, '12.0'

target 'edeesteapp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'edeesteappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end
    
  end
end

# target 'OneSignalNotificationServiceExtension' do
#   pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
# end
